import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import { Toaster } from "@/components/ui/sonner";
import { ConfettiProvider } from '@/components/providers/confetti-provider';
import { MainNavBar } from '@/components/navbar/main-navbar'
import { Navbar } from './(protected)/_components/navbar'

import { currentUser } from '@/lib/auth'

//bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-sky-200 to-zinc-300

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'iSham',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  const session = await auth();
  const user =await currentUser();

  return (
   <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          <ConfettiProvider />
          <Toaster />
          <div className = "">
               {!user? (
                <>
                    <div className="">
                       <MainNavBar />
                    </div>
               </> ):(
                <>
                <Navbar />
                </>
               )}      
          </div>   
          <main className ="h-full">             
                  {children}
                </main> 
        </body>
      </html>
   </SessionProvider>

 
  )
}
